apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: latencydeschedulerpolicies.riset.ub
spec:
  group: riset.ub
  names:
    kind: LatencyDeschedulerPolicy
    plural: latencydeschedulerpolicies
    singular: latencydeschedulerpolicy
    shortNames:
      - ldp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enabled: 
                  type: boolean
                  description: enable or disable the descheduler
                intervalSeconds:
                  type: integer
                  description: Interval (s) to start the desheduler evaluation scheme
                idleCPUThreshold:
                  type: number
                  format: float
                  description: CPU threshold (millicores) that count as idle pod
              required: ["enabled", "intervalSeconds", "idleCPUThreshold"]
